"""Export modules — Excel, PDF, CSV generation.

Generates billing reports, session lists, audit trail exports.
"""

import csv
import logging
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from models.dataclasses import Session, VacuumCycle, Penalty, AuditEntry

logger = logging.getLogger(__name__)


class CSVExporter:
    """Export data to CSV format."""

    @staticmethod
    def export_sessions(sessions: List[Session], output_path: str) -> str:
        """Export sessions to CSV file."""
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        with open(path, 'w', newline='', encoding='utf-8-sig') as f:
            writer = csv.writer(f, delimiter=';')
            writer.writerow([
                'ID', 'User', 'Microscope Type', 'Start', 'End',
                'Duration (min)', 'Status', 'Billing Tier',
                'Rate (PLN/h)', 'Discount %', 'Cost (PLN)',
                'Cancelled', 'Excluded from Invoice', 'Notes'
            ])
            for s in sessions:
                writer.writerow([
                    s.id, s.username, s.microscope_type.value,
                    s.start_time.isoformat() if s.start_time else '',
                    s.end_time.isoformat() if s.end_time else '',
                    f"{s.duration_minutes:.1f}", s.status.value,
                    s.billing_tier.value, s.effective_rate,
                    s.discount_percent, f"{s.effective_cost:.2f}",
                    s.cancelled, s.excluded_from_invoice,
                    s.notes or ''
                ])

        logger.info("Exported %d sessions to %s", len(sessions), path)
        return str(path)

    @staticmethod
    def export_vacuum(cycles: List[VacuumCycle], output_path: str) -> str:
        """Export vacuum cycles to CSV."""
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        with open(path, 'w', newline='', encoding='utf-8-sig') as f:
            writer = csv.writer(f, delimiter=';')
            writer.writerow([
                'ID', 'User', 'Command', 'Start', 'End',
                'Duration (s)', 'Status', 'Ready Time (s)'
            ])
            for c in cycles:
                writer.writerow([
                    c.id, c.username, c.command,
                    c.start_time.isoformat() if c.start_time else '',
                    c.end_time.isoformat() if c.end_time else '',
                    f"{c.duration_seconds:.0f}", c.status.value,
                    c.ready_time_seconds or ''
                ])

        return str(path)



class ExcelExporter:
    """Export data to Excel format using openpyxl."""

    @staticmethod
    def export_billing_report(
        sessions: List[Session],
        penalties: List[Penalty],
        output_path: str,
        report_title: str = "TESCAN Billing Report",
        generated_by: str = "",
    ) -> str:
        """Generate Excel billing report."""
        try:
            from openpyxl import Workbook
            from openpyxl.styles import Font, Alignment, PatternFill
        except ImportError:
            logger.error("openpyxl not installed, cannot export Excel")
            return ""

        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        wb = Workbook()
        ws = wb.active
        ws.title = "Sessions"

        # Header
        ws.append([report_title])
        ws['A1'].font = Font(bold=True, size=14)
        ws.append([f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}"])
        ws.append([f"Generated by: {generated_by}"])
        ws.append([])

        # Sessions table header
        headers = [
            'User', 'Start', 'End', 'Duration (min)',
            'Tier', 'Rate (PLN/h)', 'Discount %', 'Cost (PLN)',
            'Status', 'Notes'
        ]
        ws.append(headers)
        for cell in ws[5]:
            cell.font = Font(bold=True)
            cell.fill = PatternFill("solid", fgColor="DDDDDD")

        # Data rows
        total_cost = 0.0
        for s in sessions:
            if s.cancelled or s.excluded_from_invoice:
                continue
            cost = s.effective_cost
            total_cost += cost
            ws.append([
                s.username,
                s.start_time.strftime('%Y-%m-%d %H:%M') if s.start_time else '',
                s.end_time.strftime('%Y-%m-%d %H:%M') if s.end_time else '',
                f"{s.duration_minutes:.1f}",
                s.billing_tier.value,
                s.effective_rate,
                s.discount_percent,
                f"{cost:.2f}",
                s.status.value,
                s.notes or '',
            ])

        # Summary
        ws.append([])
        ws.append(['', '', '', '', '', '', 'TOTAL:', f"{total_cost:.2f}"])

        # Penalties sheet
        if penalties:
            ws_pen = wb.create_sheet("Penalties")
            ws_pen.append(['User', 'Amount (PLN)', 'Reason', 'Date', 'Paid'])
            for p in penalties:
                ws_pen.append([
                    p.username, p.amount, p.reason,
                    p.timestamp.strftime('%Y-%m-%d %H:%M') if p.timestamp else '',
                    'Yes' if p.paid else 'No'
                ])
            pen_total = sum(p.amount for p in penalties)
            ws_pen.append([])
            ws_pen.append(['', f"TOTAL: {pen_total:.2f} PLN"])

        wb.save(str(path))
        logger.info("Excel report saved to %s", path)
        return str(path)



class PDFExporter:
    """Export data to PDF format using reportlab."""

    @staticmethod
    def export_billing_report(
        sessions: List[Session],
        penalties: List[Penalty],
        output_path: str,
        report_title: str = "TESCAN Billing Report",
        generated_by: str = "",
    ) -> str:
        """Generate PDF billing report."""
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.units import cm
            from reportlab.platypus import (
                SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
            )
            from reportlab.lib.styles import getSampleStyleSheet
            from reportlab.lib import colors
        except ImportError:
            logger.error("reportlab not installed, cannot export PDF")
            return ""

        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        doc = SimpleDocTemplate(str(path), pagesize=A4)
        styles = getSampleStyleSheet()
        elements = []

        # Title
        elements.append(Paragraph(report_title, styles['Title']))
        elements.append(Spacer(1, 0.5 * cm))
        elements.append(Paragraph(
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')} by {generated_by}",
            styles['Normal']
        ))
        elements.append(Spacer(1, 1 * cm))

        # Sessions table
        table_data = [['User', 'Start', 'Duration', 'Tier', 'Cost (PLN)']]
        total_cost = 0.0

        for s in sessions:
            if s.cancelled or s.excluded_from_invoice:
                continue
            cost = s.effective_cost
            total_cost += cost
            table_data.append([
                s.username,
                s.start_time.strftime('%Y-%m-%d %H:%M') if s.start_time else '',
                f"{s.duration_minutes:.0f} min",
                s.billing_tier.value,
                f"{cost:.2f}",
            ])

        table_data.append(['', '', '', 'TOTAL:', f"{total_cost:.2f}"])

        table = Table(table_data, repeatRows=1)
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
            ('BACKGROUND', (0, -1), (-1, -1), colors.lightgrey),
        ]))
        elements.append(table)

        # Penalties section
        if penalties:
            elements.append(Spacer(1, 1 * cm))
            elements.append(Paragraph("Penalties", styles['Heading2']))
            pen_data = [['User', 'Amount', 'Reason', 'Date']]
            for p in penalties:
                pen_data.append([
                    p.username, f"{p.amount:.2f} PLN", p.reason,
                    p.timestamp.strftime('%Y-%m-%d') if p.timestamp else ''
                ])
            pen_table = Table(pen_data, repeatRows=1)
            pen_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
            ]))
            elements.append(pen_table)

        doc.build(elements)
        logger.info("PDF report saved to %s", path)
        return str(path)

    @staticmethod
    def export_audit_trail(
        entries: List[AuditEntry], output_path: str,
        generated_by: str = ""
    ) -> str:
        """Export audit trail to PDF (GLP compliance)."""
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.units import cm
            from reportlab.platypus import (
                SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
            )
            from reportlab.lib.styles import getSampleStyleSheet
            from reportlab.lib import colors
        except ImportError:
            logger.error("reportlab not installed")
            return ""

        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        doc = SimpleDocTemplate(str(path), pagesize=A4)
        styles = getSampleStyleSheet()
        elements = []

        elements.append(Paragraph("Audit Trail Report (GLP)", styles['Title']))
        elements.append(Paragraph(
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')} by {generated_by}",
            styles['Normal']
        ))
        elements.append(Spacer(1, 1 * cm))

        table_data = [['Date (UTC)', 'Action', 'Entity', 'Changed By', 'Description']]
        for e in entries:
            table_data.append([
                e.created_at.strftime('%Y-%m-%d %H:%M') if e.created_at else '',
                e.action.value,
                f"{e.entity_type}#{e.entity_id}",
                e.changed_by,
                (e.description or '')[:60],
            ])

        table = Table(table_data, repeatRows=1)
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('FONTSIZE', (0, 0), (-1, -1), 7),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
        ]))
        elements.append(table)

        doc.build(elements)
        logger.info("Audit trail PDF saved to %s", path)
        return str(path)
